//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "histories")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i32,
    pub date: String,
    pub chapter: i32,
    pub item_type: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::chapters::Entity",
        from = "Column::Chapter",
        to = "super::chapters::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Chapters,
    #[sea_orm(
        belongs_to = "super::item_types::Entity",
        from = "Column::ItemType",
        to = "super::item_types::Column::Index",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ItemTypes,
}

impl Related<super::chapters::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Chapters.def()
    }
}

impl Related<super::item_types::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ItemTypes.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
